//
// Created by aagui on 05-07-2026.
//

#ifndef BENJAMINROJAS_BRANDONNAVEA_IGNACIOCATALDO_TALLER2_LINKEDLIST_HPP
#define BENJAMINROJAS_BRANDONNAVEA_IGNACIOCATALDO_TALLER2_LINKEDLIST_HPP

#endif //BENJAMINROJAS_BRANDONNAVEA_IGNACIOCATALDO_TALLER2_LINKEDLIST_HPP
