//
// Created by aagui on 05-07-2026.
//

#ifndef BENJAMINROJAS_BRANDONNAVEA_IGNACIOCATALDO_TALLER2_ARTIST_HPP
#define BENJAMINROJAS_BRANDONNAVEA_IGNACIOCATALDO_TALLER2_ARTIST_HPP

#endif //BENJAMINROJAS_BRANDONNAVEA_IGNACIOCATALDO_TALLER2_ARTIST_HPP
